### ISSUE TITLE
Multiple actions and events triggered

### ISSUE THREAD

**Issue by keithvaz** [museumvictoria/nodel#19]
Node seems to be triggering multiple instances of actions or signals on some nodes, even though they are scripted to only send an action or signal just once.
I have noticed this on multiple node hosts, running on different computers and attached some example screenshots from some tests I conducted on a couple of galleries.
All the recipes are the same, and the latest version of Nodel 2.04 is running on the node hosts.

**Gallery 1 - sent the signal via the Scheduler node**
Scheduler - triggered AllOn signal at 1.20pm
![bt scheduler](https://cloud.githubusercontent.com/assets/6658474/5640110/732a1ed4-9675-11e4-8354-efa962fc3dbf.png)

Gallery - received two AllOn signals at 1.20pm
![bt gallery](https://cloud.githubusercontent.com/assets/6658474/5640196/ae7aa46c-9676-11e4-8f84-d880576ff590.png)

Exhibit - received four Enable signals and sent four Enable actions at 1.20pm
![bt exhibit](https://cloud.githubusercontent.com/assets/6658474/5640207/ddb021b2-9676-11e4-8df3-0dbf44f0e714.png)

Device - sent four PowerOn actions at 1.20pm, with two successes
![bt device](https://cloud.githubusercontent.com/assets/6658474/5640223/04f612ea-9677-11e4-90ee-c60269a07d59.png)

**Gallery 2 - sent the action via the Gallery node**
Gallery - triggered AllOn signal at 1.49pm
![mb gallery](https://cloud.githubusercontent.com/assets/6658474/5640310/00ce5488-9678-11e4-999a-2d74636afd76.png)

Exhibit - received two AllOn signals and sent two Enable actions at 1.49pm
![mb exhibit](https://cloud.githubusercontent.com/assets/6658474/5640324/4049ebfe-9678-11e4-8786-fc8b93b53641.png)

Device 1 - sent one PowerOn action at 1.49pm
![mb device 1](https://cloud.githubusercontent.com/assets/6658474/5640363/9e3a4632-9678-11e4-9ea9-fa4bfc957008.png)

Device 2 - sent four PowerOn actions at 1.49pm
![mb device 2](https://cloud.githubusercontent.com/assets/6658474/5640379/d2b7bed0-9678-11e4-889a-597372703148.png)

**Comment by keithvaz** [comment]
Updating to the latest [version 2.0.5] (https://github.com/museumvictoria/nodel/releases/tag/v2.0.5-rc1) appears to have fixed this issue. Will conduct further tests before confirming and closing this bug.

**Comment by justparking** [comment]
There has been little or no changes to the Nodel core since Apr 2014, so v2.0.5 shouldn't have made any difference. If you see this again, send me the log files in the 'logs' folder.

**Comment by justparking** [comment]
Keith, it's quite possible this issue is caused by #21. If you notice it again, please re-open this issue.
