### ISSUE TITLE
Latest version of Nodel not showing

### ISSUE THREAD

**Issue by keithvaz** [museumvictoria/nodel#20]
Even though I have updated to the latest version of Nodel v2.0.5-rc1, when I browse to a node and mouseover the Nodel logo, it still appears as v.2.0.3.

![gallery v2 0 3](https://cloud.githubusercontent.com/assets/6658474/5640881/cbd269fa-9680-11e4-8f83-f1eb3c5f62ba.png)

**Comment by justparking** [comment]
I've put up a new release ([RC2] (https://github.com/museumvictoria/nodel/releases/tag/v2.0.5-rc2)). 

In the future link the version stamp to the build-script so this can't happen again.
