### ISSUE TITLE
Computer Nodes not responding to turnoff

### ISSUE THREAD

**Issue by scienceworld** [museumvictoria/nodel#22]
I have had 2 computer nodes stop responding to TurnOff when requested from their exhibit node.  
both were running nodel 2.04.  

I tested the exhibit node and changed the computer off to turn off another node which worked.  I could see in the computer node a received TurnOff command.  I deleted and reinstalled nodel and put a fresh computer recipe on the machine. same effect.

Computer 1, renamed to a different node name other than its original and then responded to off commands.  renamed back to original and did not respond.

Computer 2.  upgraded to nodel 2.05, renamed node.  no affect.  The computer node does not receive the off command even though the exhibit node is correctly associated and is sending other commands.

![image](https://cloud.githubusercontent.com/assets/3997916/5641889/96a59bb6-95f5-11e4-9f2a-76982f127f3e.png)

![image](https://cloud.githubusercontent.com/assets/3997916/5641892/9df598da-95f5-11e4-8a28-78140df6e206.png)

I enabled logging and no logs were generated when the exhibit node was sending of off command.

the Nodel Server is running nodel 2.05.

**Comment by justparking** [comment]
That's odd. I've got a few questions but it might just be easier if we can view some of the logs. You mention you couldn't produce any so can you make sure the following's in place:

*For both the "server" and "edge" node hosts, create the following `bootstrap.json` file:*

```json
{
    "enableProgramLogging": true
}
```

(That file should reside right next to the `_bootstrap_example.json`, `.version`, etc. files i.e. the root.)

You'll need to restart those hosts and what you'll should start seeing is a pile of `.log` files in the `logs` folder:

* ChannelClient.log
* ChannelServer.log
* Discovery.log
* NodelClients.log
* NodelServers.log
* program.log

(above list taken from my freshly downloaded 2.0.5 with logging enabled.)

Once you catch the edge nodes not responding, can you grab some of the relevant `program.log` logs and post them here (central and edge). Or even ZIP them all up and email me. I could even grab your `nodes` folder and re-produce things here if needed.

Cheers.

Justin

**Comment by scienceworld** [comment]
Jan 4th and Jan 5th "RecyclingGame" and then later called "RecyclingGameComputer" didn't shut down.

I enabled logging, but the computer did not log anything. all logs were 0 bytes.
See issue #21 for the logs that would cover this time from the host.

The other computer that had the issue was "Stepandshoot" and renamed to "StepAndShootComputer" and then did work.  Logs were 0bytes when the node didnt receive its shutdown command.  this was 12/31/2014, 1/2/2014

**Comment by justparking** [comment]
We need to resolve why **RecyclingGameComputer** and **StepAndShootComputer** aren't producing any logs as that's a fundamental function of Nodel and could be the cause of your problem.

Are they Window's PCs running Nodel with the service wrapper?

Can you try directly from a command prompt and dump any error reports?

*From your Nodel directory:*

`> java -jar nodelhost-2.0.5-rc2.jar`

If possible, I'd like to see your environment dump which should be at the top of the log. It could be the combination of the Java service wrapper and the version of Java you're using. I can try and reproduce that here.

**Comment by scienceworld** [comment]
Widows 7
Java v1.8.0.25-b18

![image](https://cloud.githubusercontent.com/assets/3997916/5667142/3534c624-971a-11e4-8669-554a871c4855.png)

StepAndShootComputer produces logs, but not on startup.  All the logs get reset to 0bytes and eventually the discovery log gets entries

RecyclingGameComputer hasn't produced any logs via console or service.  I even went in and produced an action and still no log.

**Comment by scienceworld** [comment]
Had another instance of a computer not responding

Was running v2.03 under WaterGunGame
nodel host sent off command, and nodel on watergungame didnt receive it, and logs didnt change.
updated computer to v2.05 with no change
renamed node WaterGunGame to WaterGunGameComputer as well as exhibit node action.  
Computer received the off command.

nodel host logs. http://we.tl/nL1PyohTOp 

I did notice some reoslution failures and some backoffs revolving around the WaterGunGame node in the host's logs.

**Comment by justparking** [comment]
In your previous report, you say "Computer received the off command." - So does that mean the nodes are communicating but the actual Python function is not performing what you want it to do i.e. call shutdown?

Because of this, I'm not convinced issue #21 affects this issue. Regardless, you should probably keep things consistent. Can you update it and let me know if you're still seeing the problem.

**Comment by scienceworld** [comment]
2 computers, RecyclingGame and WaterGunGame both failed to receive their off commands.

Under activity they do not get the signal to shut down.

On exhibit nodes where the computer is working, shortly after the computer shuts down the exhibit node registers a ResolutionFailure for the poweroffcomputer action.  To me this is because the comptuer is offline, and the exhibit node and computer node bindings are breaking due to the computer being unavailabile.

The exhibit nodes where the computers are not receiving their action to shut down we do not get a resolution failure message.  In fact, for the problem computers the last time they got it was the 23rd of January.

![image](https://cloud.githubusercontent.com/assets/3997916/5942335/b3ba2fe6-a6cb-11e4-9143-a907023429c1.png)

Even if I dont use the exhibit node to disable the exhibit, and I shut down the computer manually I still get the resolutionfailure within the node.

To me it seems that these 2 problematic nodes are failing to bind themselves to the exhibit node dynamically and are not listening for their signals.

that might explain why the logs on these two problematic computers are not populating.  something might not work properly.

**Comment by scienceworld** [comment]
Many of our exhibit nodes get a "Wired" message when a computer powers up indicating the action is wired to the exhibit node.  the problematic exhibits are not doing this

![image](https://cloud.githubusercontent.com/assets/3997916/5942450/8542241a-a6cc-11e4-9f68-6f4a0f3bfadf.png)

**Comment by justparking** [comment]
Yes, if the status of the binding isn't 'Wired', it means there's no event/action link present so those computers would not receive the events they're interested in.

In this case I suspect there is problem during the node-name resolution and it could be caused by an intermittent multicasting issue.

All of that activity is stored in the program logs in the **logs/Discovery.log** file. Can we take a look at that on on the client and server? It should show clearly what each host is sending and what it is "hearing" on the network.

I've seen IGMP (IP multicasting) do strange depending on the underlying network. From a layer-2 & 3 networking point-of-view, are those PCs any different to the ones that work reliably? (e.g. are they on different subnets? different edge switches? etc.)

Also, how are those computers being shutdown and woken up i.e. are they issued a 'sleep', 'hibernate' or 'full shutdown'?

**Comment by justparking** [comment]
I forgot to add, there is a stand-alone Nodel browser that can be run directly via a Chrome app (*) that you might find useful:

https://chrome.google.com/webstore/detail/nodel-browser/mdemaomhdbgmndbnappehdcddihhjedb?hl=en

It's a very rudimentary app but it does a good job of discovering and launching into the Nodel network. I keep it pinned to my Windows taskbar.

The logs will probably tell us anyway, but when you notice those computers are not wiring up correctly, it might be useful to run the app from them to determine what their view of the Nodel network is.

(*) We have published the Nodel Browser Chrome application under our software entity for Google development which is called "Automatic". It's still open source and can be found alongside the other Nodel code in this repository here: [nodelbrowse-chromeext] (https://github.com/museumvictoria/nodel/tree/master/nodelbrowse-chromeext).

**Comment by scienceworld** [comment]
I'll try the chrome extension.

I do notice that these machines do not append their logs until much much much later after start up. Sometimes not at all.

Sent from my iPhone

On Jan 28, 2015, at 5:43 PM, Justin Parker <notifications@github.com<mailto:notifications@github.com>> wrote:


I forgot to add, there is a stand-alone Nodel browser that can be run directly via a Chrome app (*) that you might find useful:

https://chrome.google.com/webstore/detail/nodel-browser/mdemaomhdbgmndbnappehdcddihhjedb?hl=en

It's a very rudimentary app but it does a good job of discovering and launching into the Nodel network. I keep it pinned to my Windows taskbar.

The logs will probably tell us anyway, but when you notice those computers are not wiring up correctly, it might be useful to run the app from them to determine what their view of the Nodel network is.

(*) We have published the Nodel Browser Chrome application under our software entity for Google development which is called "Automatic". It's still open source and can be found alongside the other Nodel code in this repository here: nodelbrowse-chromeext<https://github.com/museumvictoria/nodel/tree/master/nodelbrowse-chromeext>.

-

**Comment by justparking** [comment]
Just letting you know that I think I might have been able to reproduce your condition by really messing around with a Wifi interface on an old laptop. The Nodel code should be resilient to these things but I'm seeing if even more code might ensure the IGMP operations remain reliable always. So before you do anything, let me complete my testing...

**Comment by scienceworld** [comment]
Thanks!

I hope there's something for find/fix.

A third computer was missed last night. Wheelchairacer.

Sent from my iPhone

On Jan 29, 2015, at 1:04 AM, Justin Parker <notifications@github.com<mailto:notifications@github.com>> wrote:


Just letting you know that I think I might have been able to reproduce your condition by really messing around with a Wifi interface on an old laptop. The Nodel code should be resilient to these things but I'm seeing if even more code might ensure the IGMP operations remain reliable always. So before you do anything, let me complete my testing...

-

**Comment by scienceworld** [comment]
One interesting tidbit.

If I go to the exhibit node, and delete a character of the computer name for poweroff, and pick from the auto complete list, the exhibit will rebind with the computer and we receive a wired event for poweroffcomputer

Is the node name case sensitive?

**Comment by justparking** [comment]
This issue was caused by a bad port number being temporarily broadcast by a client. That, in turn, tripped up part of the server's "node maintenance" routine. It explains all the symptoms you observed.

The condition is timing sensitive which means it could have been happening on other clients, although **RecyclingGameComputer** was clearly more susceptible to it than the others.

The client does eventually correct its port information but by that stage, the server is left crippled until its binding handler is completely reset.

I have patched both the client and server related code.

**Note:** I'd suggest you first target the server with the update and confirm the update has worked. It's not absolutely essential you update the client(s), but you can do so in the future as you please.
