### ISSUE TITLE
"title" schema attribute ignored for actions and events

### ISSUE THREAD

**Issue by justparking** [museumvictoria/nodel#25]
By example, these action and event definitions don't display as expected:

```py
def local_action_PowerOn(arg = None):
  """{"title":"On","desc":"Turns this node on.","group":"Power","caution":"Ensure hardware is in a state to be turned on."}"""
```

```py
local_event_Triggered = \
    LocalEvent('{"title":"Sensor is triggered","desc":"When this sensor is triggered.","group":"General"}')
```

The UI currently shows **PowerOn** and **Triggered** for the action and event buttons respectively, when they should be **On** and **Sensor is triggered**.

It would be nice to be able to use more decorative text (spaces, punctuation, etc.), but more importantly, where large numbers of buttons are visible, being able to manage the titles could mean much cleaner interfaces. 

For example, `"group":"Input"` already provides context, this list could be cleaned up from:
* InputVideo1
* InputVideo2 
* InputVideo3
* InputVideo4
* InputDVD
* InputTape
* InputCD
* InputFM
* InputAM
* InputTuner
* InputMultiCh
* InputXM
* InputSirius

To:
* Video 1
* Video 2 
* Video 3
* Video 4
* DVD
* Tape
* CD
* FM
* AM
* Tuner
* MultiCh
* XM
* Sirius

**Comment by mcartmel** [comment]
Actions and Events now use title as the button name, where available.
