### ISSUE TITLE
Bracket in group name affects UI rendering

### ISSUE THREAD

**Issue by justparking** [museumvictoria/nodel#27]
By example, using this definition will prevent actions and events from rendering.
```json
{ "title": "Turns on",
  "desc": "Turns this node on.",
  "group": "Power (Main)",
  "caution": "Ensure hardware is in a state to be turned on." }
```

**Comment by justparking** [comment]
Brackets are just what affected me. I assume it's an escaping issue and other special characters, e.g. '#', might have the same effect.

**Comment by mcartmel** [comment]
Characters that are important to Javascript were not being stripped from the group name. Now fixed.
