### ISSUE TITLE
DST timechange

### ISSUE THREAD

**Issue by scienceworld** [museumvictoria/nodel#28]
Hi Guys.

Nodel gets its time from the machine its running on, in this case windows.  windows will perform its daylight savings time change this weekend.

Will the nodel server sense the local time has changed and recalculate all the countdown timers to next event, in this case a startup event?

I know that the schedulers use a delta from the last event to the next event and decrements the countdown once per second, and there doesnt seem to be any apparent recalculation of that delta until the next event is triggered so i'm worried that a time change will go unnoticed until the next event.

Please advise.

**Comment by mcartmel** [comment]
Just following up on open issues. Nodel uses the APScheduler library for Python in the advscheduler recipe. This library accounts for DST when calculating event triggers, so events should be triggered at the correct time in Nodel.
