### ISSUE TITLE
Broken link in wiki

### ISSUE THREAD

**Issue by keithvaz** [museumvictoria/nodel#29]
Broken link in OS X install wiki - https://github.com/museumvictoria/nodel/wiki/Install-Nodel-as-an-OS-X-process - Java 7 "two files require patching"

**Comment by scienceworld** [comment]
Can we link to an already compiled and ready to go java binary for osx to make rapidly deploying to macs easier?

**Comment by justparking** [comment]
I've dug up a previous article and I think this is what the link should be:
https://issues.apache.org/jira/browse/DAEMON-281

I'll update the wiki.

We should also be going straight to Java 8 instead (Nodel should still be 100% compatible with 8). Oracle is actively phasing out 7. Not sure if that patch is still applicable. Perhaps someone can test?

Agreed on making it easier to deploy on Macs. @mcartmel has been most involved in that side of things. Perhaps he can comment on feasibility?

**Comment by justparking** [comment]
Wiki updated. Will create a new issue to cover streamlining OS X service installation.
