### ISSUE TITLE
OS X Install process fail or unclear

### ISSUE THREAD

**Issue by justinatomatic** [museumvictoria/nodel#31]
I'm following this guide

https://github.com/museumvictoria/nodel/wiki/Install-Nodel-as-an-OS-X-process

I'm up to "Run on the console(for testing):"

When I run sudo /Library/Nodel/jsvc -server -cwd /Library/Nodel -home /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home -pidfile /var/run/jsvc.pid -cp /Library/Nodel/nodel.jar org.nodel.nodelhost.Service

It returns without any output to the terminal so it's hard to tell if it succeeded or failed and as far as I can tell nothing is running the the background. 

Also you mention 

"After running this test, you should be able to view Nodel in a browser."

But don't say on what port to expect the interface.

**Comment by mcartmel** [comment]
The default port is 8085; I've updated the guide, thanks for pointing this out.

Does nodel run correctly when you execute it directly? 
```java -jar nodel.jar```

**Comment by justinatomatic** [comment]
No it doesn't I get the following error. 
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/nodel/jyhost/Launch : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

And for the record java -version gives
```
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)
```

And I'm running OS X 10.10.4

**Comment by mcartmel** [comment]
You will need to install a minimum of Java 7 now as Java 6 is being aggressively phased out and we have been forced to drop support for it in Nodel.

See [this article](https://www.java.com/en/download/help/mac_java_update.xml) on the Java site for further information.

**Comment by justinatomatic** [comment]
Cool It's running via "sudo java -jar nodel.jar" after installing a current JDK.

You might want the change the OS X Docs to require a current JDK and not mention running it under Java 6.

So now I have a UI 

![nodelui](https://cloud.githubusercontent.com/assets/3860848/8974811/9e9642ac-36b9-11e5-9742-f989b77ee3a8.png)

But it's not really obvious what the next step is. 

But as for the java issue that solved and you can close the issue.

**Comment by keithvaz** [comment]
You have Nodel up and running, which is great!

Now you need to create some nodes, which you can do by following this [guided video] (https://vimeo.com/113455943). There is no voiceover yet as we are currently working on it.

You can also download some [recipes] (https://github.com/museumvictoria/nodel/tree/master/recipes).

Thanks for using Nodel and for your input.

**Comment by justinatomatic** [comment]
Thanks for the links I had not found the videos myself. The video could be in a higher resolution as its pretty difficult to read the text at that size.

**Comment by mcartmel** [comment]
Thanks for all the feedback. I'll close this for now.
