### ISSUE TITLE
Nodel 2.1.1 non functioning node issues 

### ISSUE THREAD

**Issue by scienceworld** [museumvictoria/nodel#44]
tried the new release of nodel 2.1.1 today on our main nodel server.

1. gallery nodes no longer had actions
2. schedule nodes only displayed the nodel logo and no node information.
3. the nodel diagnostic console complained verbosely about deadlocks

`16-02-04 08:18:27 [nodeloneoff_31] [org.nodel.jyhost.PyNode_30_MinidomePower] The interlocked initialisation sequence of the scripting engines is slow or dead-locked. A new lock has been created to hopefully release any potential dead-lock.
16-02-04 08:18:38 [nodeloneoff_48] [org.nodel.jyhost.PyNode_47_HaloPower] The interlocked initialisation sequence of the scripting engines is slow or dead-locked. A new lock has been created to hopefully release any potential dead-lock.
16-02-04 08:18:48 [nodeloneoff_69] [org.nodel.jyhost.PyNode_66_2ndCirculationGallery] The interlocked initialisation sequence of the scripting engines is slow or dead-locked. A new lock has been created to hopefully release any potential dead-lock.
16-02-04 08:19:25 [nodeloneoff_156] [org.nodel.jyhost.PyNode_155_AlpineRacerWOL] The interlocked initialisation sequence of the scripting engines is slow or dead-locked. A new lock has been created to hopefully release any potential dead-lock.
16-02-04 08:19:36 [nodeloneoff_160] [org.nodel.jyhost.PyNode_159_OurWorldConveyorBeltExhibit] The interlocked initialisation sequence of the scripting engines is slow or dead-locked. A new lock has been created to hopefully release any potential dead-lock`

I have rolled back my nodel build.

**Comment by scienceworld** [comment]
Let me clarify on issue 1 above

Gallery nodes never had actions, they have signals.
in nodel 2.07 I could press the all off signal and all exhibit nodes bound to the gallery would turn off.
in nodel 2.11 I cannot press the all off signal. the button is flat and isn't pressable.

v2.07
![image](https://cloud.githubusercontent.com/assets/3997916/12822188/adf36788-cb1b-11e5-8a46-bdafec12d119.png)

v2.11
![image](https://cloud.githubusercontent.com/assets/3997916/12822199/bd726f74-cb1b-11e5-9929-32e2b85c1a43.png)

**Comment by justparking** [comment]
I've addressed these in the following issues:
* #45 
* #47 
* #46 

(closing)
