### ISSUE TITLE
Schedule nodes only display the nodel logo and no node information

### ISSUE THREAD

**Issue by justparking** [museumvictoria/nodel#47]
In #44, @scienceworld wrote:
> schedule nodes only displayed the nodel logo and no node information

**Comment by justparking** [comment]
Michael, I think I've come across this too. I believe it's simply missing some files (js or html) from its content.

Can you please test the official **scheduler** and **advscheduler** [recipes](https://github.com/museumvictoria/nodel-recipes) on old and latest versions of Nodel.

**Comment by mcartmel** [comment]
The custom HTML for this recipe is referencing an older version of jquery which was updated in Nodel core a while ago. Updated to match the correct version.

**Comment by scienceworld** [comment]
we had some customizations to the advscheduler to process its scheduled job even if it "missed" it.  should I just replace the html file or do you think the new scheduler recipe shouldnt have a missed event problem anymore?

**Comment by scienceworld** [comment]
replacing the html file fixed the issue, thanks.
