### ISSUE TITLE
Cannot get nodel to see local nodes on osx

### ISSUE THREAD

**Issue by igitthatalot** [museumvictoria/nodel#49]
I just got nodel running on osx. I can view the webpage and see other nodes, however any node i create on the osx client i cannot see from either its web interface, or any other nodes web interface. I am attaching a log file which shows that it is finding the node "macminiCOMPUTER" however when i go to search it on the webpage it does not appear. It is not there. Any steps from here? I am using latest jar file 2.1.1
[general_2016-02-19_10h00.log.txt](https://github.com/museumvictoria/nodel/files/138495/general_2016-02-19_10h00.log.txt)

I also made another node using the web interface called test, it is created, the folder is created under nodes however i cannot find it using the web interface.
![cannot find node](https://cloud.githubusercontent.com/assets/12143187/13185185/a2cc3742-d6f4-11e5-87cb-45d67d612457.png)

let me know what other steps i can take to diagnose.

**Comment by mcartmel** [comment]
Do you know if the newly created node is actually starting? ie. Can you load the interface for the node directly? eg. http://localhost:8085/nodes/test

**Comment by igitthatalot** [comment]
Thats correct. I can load the node directly, but i cannot see it anywhere else. I can also not see the machine name, or the node test, from this or any other host.

![2016-04-25_08h57_01](https://cloud.githubusercontent.com/assets/12143187/14789968/f58fcdf6-0ac3-11e6-8dc7-baed9fb406c5.png)
![2016-04-25_08h59_29](https://cloud.githubusercontent.com/assets/12143187/14789991/10fef29c-0ac4-11e6-8124-209cf3d2b939.png)


those other test entries are other things. Nothing labeled simply 'test'.

**Comment by eaban01** [comment]
Hey guys, I'm having the exact same problem,  Just wondering if anyone's found a solution yet?
Cheers

**Comment by justparking** [comment]
I think I finally got to the bottom of this. There was an obscure difference in behaviour the way Java creates a multicast socket on Windows & Linux compared to OSX.

Please see the latest release related to the update [here](https://github.com/museumvictoria/nodel/releases/tag/v2.1.1-update_osxmcsocket_rev192).

This also fixes another issue where the "cannot assign address" was repeatedly logged and required the `-Djava.net.preferIPv4Stack=true`. This should not be needed now.

I've tested it on my OSX, Windows and Linux gear. Let me know how you go on yours.

If I get positive feedback I'll push out a new official release.

**Comment by igitthatalot** [comment]
I can confirm that you have fixed the issue with the linked build. i can now see the node, and also successfully shut it down! now the next fun part, getting WOL working on the mac....

**Comment by justparking** [comment]
Thanks for the feedback. Have release a new release with the bugfix and a few other updates. See [v2.1.1-release196](https://github.com/museumvictoria/nodel/releases/tag/).
