### ISSUE TITLE
No fallback to HTTP when websockets are unavailable

### ISSUE THREAD

**Issue by justparking** [museumvictoria/nodel#54]
As per title, when proxies are involved, direct websockets might not be available. An automatic fallback under these conditions would be very useful otherwise much of the event & actions states and activity is not transmitted.

Chrome error shows this:
![image](https://cloud.githubusercontent.com/assets/5266533/14522073/27995936-0270-11e6-8a52-0de064ea5bc8.png)

**Comment by mcartmel** [comment]
Nodel interface now falls back to polling if WebSocket fails. 
You can also now force polling in the query string using
`?poll=true`
