### ISSUE TITLE
Date picker does not appear on Scheduler node in Safari or Firefox browsers

### ISSUE THREAD

**Issue by keithvaz** [museumvictoria/nodel#9]
The date picker only appears in the Scheduler node only appears on the Chrome browser and not in Safari or Firefox in OS X.
The date picker does appear in the Safari browser in iOS.
This means users cannot select a date to filer schedules.

The date format in Safari and Firefox is different to Chrome.

Chrome
![scheduler - chrome](https://cloud.githubusercontent.com/assets/6658474/4587068/75680c16-5024-11e4-9412-0ac28ff6256f.png)

Firefox
![scheduler - firefox](https://cloud.githubusercontent.com/assets/6658474/4587070/756ab9ac-5024-11e4-86bd-7acbebe0b8f2.png)

Safari
![scheduler - safari](https://cloud.githubusercontent.com/assets/6658474/4587069/756874bc-5024-11e4-959e-276cf612d2c9.png)

**Comment by keithvaz** [comment]
Updating to the latest version of [nodel.js] (https://github.com/museumvictoria/nodel/blob/master/nodel-webui-js/www/js/nodel.js) will fix the date-picker issue in Chrome.

I'll leave this open as it still doesn't work in Safari (desktops only) and Firefox.

**Comment by justparking** [comment]
*Since this marked as `wontfix`, I'm closing it so it's off the main list of issues that will or need to be addressed in the near future. It still stays recorded as an issue.*
